### ISSUE TITLE
How does it compare to BedrockDB?

### ISSUE THREAD

**Issue by wmertens** [canonical/dqlite#159]
One for the FAQ: I think https://bedrockdb.com/ is based on Paxos and dqlite is based on Raft? Any comments on the differences?

**Comment by freeekanayaka** [comment]
Bedrock is not meant to be embedded, it's a standalone database. Raft is wildly regarded as safer because it's easier to understand. Paxos is known to be extremely hard to implement right.

**Comment by changloong** [comment]
Bedrock only use Paxos for leader select,  and use `Quorum Consensus` for database operate.

Dqlite use Raft for database operate.

**Comment by wmertens** [comment]
@changloong so which implications might that have?

**Comment by changloong** [comment]
check here: https://github.com/canonical/dqlite/issues/160#issuecomment-623948376
