### ISSUE TITLE
The xFrames replication hook can be called within sqlite3_step()

### ISSUE THREAD

**Issue by freeekanayaka** [canonical/dqlite#163]
The gateway code assumes that calls to ```sqlite3_step()``` are always synchronous, but that might not be the case.

**Comment by freeekanayaka** [comment]
> @freeekanayaka Any idea if this is still relevant? `xFrames` doesn't seem to exist anymore in dqlite.

I believe this one can be closed. There should be a scenario like this in the dqlite test suite, basically checking what happens when a transaction performs a page cache spill (i.e. writing to the WAL one or more uncommitted dirty cache pages to free up slots in the cache). It's probably worth checking that this is indeed properly tested.

**Comment by MathieuBordere** [comment]
tested here https://github.com/canonical/dqlite/blob/35b5418af73d5112c156d05eec2ad85268707cb3/test/integration/test_vfs.c#L442
