### ISSUE TITLE
Relax size limit on transactions

### ISSUE THREAD

**Issue by freeekanayaka** [canonical/dqlite#166]
This is relevant for cases like https://github.com/lxc/lxd/issues/6322

**Comment by ubojan** [comment]
Hi, do you know when this might be solved? There are number of instances with "broken" lxd (regarding https://github.com/lxc/lxd/issues/6322), but containers running.
If it will take considerable amount of time, we might bite the bullet and perform advised workaround (delete old snapshots) on all instances.

**Comment by freeekanayaka** [comment]
@ubojan I still have to check the details but it most likely will require some time to fix this issue.

However, I think we can workaround the issue by committing the change in smaller transactions. I can try to have a stab at that if you wish (it might require a new lxd release, but maybe not if we're lucky).

**Comment by ubojan** [comment]
That would be cool!

**Comment by freeekanayaka** [comment]
I'll try to look at the situation tomorrow and let you know.

**Comment by freeekanayaka** [comment]
Unfortunately coming up with a simple workaround is more complicated than I thought, mainly because the patch that upgrades from version 15 to version 16 of the database schema is hard to break down in smaller pieces.

I've also given a quick look at how long the proper fix (which should be made in libraft) might take and I think it's a few days of work, so not something straightforward. We want to have it fixed as well, but I have to sync with @stgraber about the priority of it, as we have a few other things.

**Comment by stgraber** [comment]
@freeekanayaka dqlite fixes for our users take priority over other work, so lets get this one sorted, then go back to the DB tooling in LXD and then onto the rest so long as no other important issues pop up in between

**Comment by ubojan** [comment]
@freeekanayaka thanks for the update and for the provided (delete old snapshots) workaround. @stgraber thanks for assigning this ticket high priority.
I've went ahead and fixed lxd service using workaround on affected instances.
Also dqlite fix is highly appreciated as we have lots of instances still on 3.16 and 3.17 and would like them to update to latest version.

**Comment by freeekanayaka** [comment]
This has been fixed in raft https://github.com/canonical/raft/pull/85.

So lxd 3.19 should be able to upgrade from any previous version (e.g. 3.16 and 3.17 in your case) without hitting "transaction too big" error.
