### ISSUE TITLE
sqlite CLI?

### ISSUE THREAD

**Issue by ibuildthecloud** [canonical/dqlite#173]
I don't know if this makes technical sense, but would it possible to have a sqlite CLI that works off the state on disk?  I find the biggest thing I miss running dqlite over a sqlite setup is that I don't know how to just run the sqlite CLI and run ah hoc queries to troubleshoot.

**Comment by freeekanayaka** [comment]
Yes, this should something we'd want to add. Some simplistic tool written in Go which uses the go-dqlite client and allows to run basic queries shouldn't be to difficult to write.

One other option in the meantime is to use the ```client.Client.Dump()``` API to get the content of a database: if you write that to disk you can inspect it using the regular sqlite3 CLI.

**Comment by freeekanayaka** [comment]
One slight difficulty is that applications usually are expected to customize the way they expose a ```dqlite.Node``` over the network, proxing incoming connections and setting up a custom dial function that performs things like TLS, application-specific authentication, HTTP connection upgrade, etc.

So I'm not sure how to teach this to the CLI tool. Initially the CLI might just support setups were the ```dqlite.Node``` is exposed over plain TCP using the default dial function.

**Comment by stgraber** [comment]
We have support for this in the demo codebase in go-dqlite and otherwise expect whoever embeds dqlite to make such an interface available should they want to. It's unlikely that we'll be writing a standalone (non-demo) client given that the actual transport used by dqlite is up to the implementor and so the client wouldn't know how to connect.

**Comment by freeekanayaka** [comment]
> We have support for this in the demo codebase in go-dqlite and otherwise expect whoever embeds dqlite to make such an interface available should they want to. It's unlikely that we'll be writing a standalone (non-demo) client given that the actual transport used by dqlite is up to the implementor and so the client wouldn't know how to connect.

Note that the default CLI sported in the `go-dqlite` package is actually not the demo program (under `cmd/dqlite-demo`) but rather an actual non-demo standalone program (under `cmd/dqlite`). It's true that such default CLI won't work in all cases (for example LXD uses its own transport), but it will work fine if you use the `app` helper, as it's recommended these days. In that case you can pass to the default CLI the TLS certificate for authenticating.
