### ISSUE TITLE
what to do when quorum is lost

### ISSUE THREAD

**Issue by ibuildthecloud** [canonical/dqlite#175]
When quorum is lost what is the procedure to restore the cluster?  What I'm currently trying to do now is manually pick one master and just remove all peers from it.  That doesn't seem to go anywhere until I actually restore the peers.  I understand that membership change probably requires quorum (as it should), but I need some "emergency reset" mechanism.

**Comment by freeekanayaka** [comment]
Look at ```Node.Recover()```. See the docstring of the underlying [```dqlite_recover```](https://github.com/canonical/dqlite/blob/master/include/dqlite.h#L147) C API for details.

**Comment by ibuildthecloud** [comment]
Awesome, thanks!

**Comment by freeekanayaka** [comment]
You're welcome!

It most probably goes without saying, but I forgot to mention that if you have only one node that you want to recover (like it seems to be the case for you), you can just run ```Node.Recover()``` on it passing to that method a single-node configuration with only that node and you'll be good.
