### ISSUE TITLE
recover failed with error code 1

### ISSUE THREAD

**Issue by ibuildthecloud** [canonical/dqlite#176]
I'm testing error scenarios and trying to call Node.Recover() just returns an error "recover failed with error code 1"  I'm not sure where to go from here.  I have a two node cluster and trying to reset it back to just one node.

**Comment by ibuildthecloud** [comment]
Sorry, there isn't a lot of info in this issue.  I think I'm asking if there is somewhere I should look to troubleshoot a bit further.  If I can't make any progress I'll try a small use case to reproduce.  Right now I'm running this in the full context of k3s.

**Comment by ibuildthecloud** [comment]
I figured out that https://github.com/canonical/dqlite/blob/b7c20af9a1811e5286a6e02db8ef96bd6d5adcf0/src/server.c#L652 effectively masks the error.  Removing that line I can now get the error from libraft which gives me something to work off of.

**Comment by freeekanayaka** [comment]
Yeah, error propagation between dqlite and raft is currently sub-optimal. I'm working to improve the situation and provide better diagnostic messages for situations like this.

Hope that hacking around the code helps you to spot what's wrong, otherwise let me know.

**Comment by ibuildthecloud** [comment]
On line https://github.com/canonical/raft/blob/25805d9a7c73c4e401e87ff7df67e50efa5db03a/src/raft.c#L136
recovery checks that the node is unavailable.  In my situation the node is in state RAFT_FOLLOWER so recover fails.

The full scenario is this.

1. Start two nodes.
2. Kill node two
3. Node one (because of my application) will kill itself because quorum is lost
4. All nodes are shut off
5. Start node one in "recovery" mode.
6. Node.Recover() fails because node is in FOLLOWER state.

All I'm doing effectively in the code is 
```golang
	node, err := dqlite.New(id, advertiseAddress, dbDir,
		dqlite.WithBindAddress(bindAddress),
		dqlite.WithDialFunc(dial),
		dqlite.WithNetworkLatency(20*time.Millisecond))

node.Start()
node.Recover(singleNode)
```

**Comment by ibuildthecloud** [comment]
So right now removing the "UNAVAILABLE" check in libraft everything works as expected.

**Comment by freeekanayaka** [comment]
Okay, the intended way to use ```Node.Recover()``` is **before** ```Node.Start()```, see the docstring of the low-level ```dqlite_node_reover()``` C API:

```
 * 1. Make sure no dqlite node in the cluster is running.
```

(which translates to "make sure that ```Node.Start()``` wasn't called yet).

I think there is some work to do both in improving documentation and reporting better errors.

**Comment by freeekanayaka** [comment]
Note that removing the "UNAVAILABLE" check would make the API unsafe. It might turn out to work in your specific case only by chance.

**Comment by ibuildthecloud** [comment]
@freeekanayaka I tried not starting the node and I got a connection error.  I think maybe I was doing something wrong.  I'll try again.  Thanks.

**Comment by ibuildthecloud** [comment]
@freeekanayaka Thanks, I found the issue. Prior to doing the reset I was contacting the node to find the surviving members ID.  Due to my lack of understanding of IDs I didn't want to assume on the client side I had the right ID for the surviving node.  I'm guessing I don't have to do that?  In my use case I only support resetting the cluster to one member.  In that situation I assume I can just hard code the ID to 1?  Actually is ID 1 required?

**Comment by freeekanayaka** [comment]
> @freeekanayaka Thanks, I found the issue. Prior to doing the reset I was contacting the node to find the surviving members ID.

I'm not surely to understand what you mean here.

> Due to my lack of understanding of IDs I didn't want to assume on the client side I had the right ID for the surviving node. I'm guessing I don't have to do that?

I'm not clear about this as well.

> In my use case I only support resetting the cluster to one member. In that situation I assume I can just hard code the ID to 1? Actually is ID 1 required?

The use case of resetting the cluster to one member should be indeed be one of the most frequent and should also be pretty straightforward to handle. As long as you:

1. Use ```1``` for the ```id``` parameter of ```dqlite.New()```
2. Use ```1``` for the ```ID``` attribute of the single ```dqlite.NodeInfo``` object that you pass to ```Node.Recover()```

you should be good, regardless of what ID the node actually had before.

**Comment by ibuildthecloud** [comment]
Thanks, everything is working now.
