### ISSUE TITLE
failed to set bind address

### ISSUE THREAD

**Issue by ibuildthecloud** [canonical/dqlite#177]
I killed a node and then tried to start it again and it failed with "failed to set bind address."  I'm using abstract unix sockets ("@....") for the bind address.  I'm not a C programmer, so forgive me if this is way off base, but is it possible when the bind address is set the FD is not set to FD_CLOEXEC?  My process that runs dqlite also spawns children and I suspected that a child process was holding onto the unix socket.  After killing all orphan children it released the socket and I was able to start again.

**Comment by freeekanayaka** [comment]
It's possible yes. I guess using ```FD_CLOEXEC``` would be wise indeed. I'll look into this.
