### ISSUE TITLE
question: sqlite errors

### ISSUE THREAD

**Issue by ibuildthecloud** [canonical/dqlite#180]
When running go-dqlite database/sql driver, if an error is returned from the driver, will it be an instance of `sqlite3.Error` with all the same codes as the mattn/go-sqlite3 driver?

**Comment by ibuildthecloud** [comment]
From testing is seems that bindinds.Error is returned.  I will see if I can use that structure.

**Comment by ibuildthecloud** [comment]
Closing this issue in favor of https://github.com/canonical/go-dqlite/issues/55

**Comment by freeekanayaka** [comment]
Note that I'd like to avoid the go-dqlite ```database/sql``` driver to return ```sqlite3.Error``` because the latter would require to pull in CGO in the go-dqlite driver, which should not be needed (since the Go dqlite driver speaks to dqlite over the network).
