### ISSUE TITLE
Suspected int overflow or encoding issue

### ISSUE THREAD

**Issue by ibuildthecloud** [canonical/dqlite#182]
Running dqlite on a Raspberry PI (armhf 32bit) crashes almost immediately with the following error (sorry it's a screen shot) ![](https://user-images.githubusercontent.com/6358735/69915482-4a4cc480-1447-11ea-9795-d6959fbf7f7f.png)

The line is failing on is go-dqlite is
```
	size := m.getUint64()
	data := make([]byte, size)
```
Just some wild guess would be a uint32 got encoded on the stream and now decoded as a uint64 in go.

This is was reported in k3s https://github.com/rancher/k3s/issues/1155.

The way that dqlite is compiled is here https://github.com/rancher/dqlite-build/blob/1e83a1fa426219abbba572b406e8acd2749e8b5a/Dockerfile#L57. One thing that could be causing this issue is that we compile armhf on a arm64 host.  The user space and compiler are all compiled for armhf but it is possible some platform detection logic is querying the CPU/kernel and not the build environment.

**Comment by ibuildthecloud** [comment]
I suspect this line https://github.com/canonical/dqlite/blob/3ed153a99a589e18ca13be9b6a3039493e8b5ec4/src/query.c#L59

**Comment by ibuildthecloud** [comment]
This is going past my comfort level with C, but I think in then generated encoder for message, this code below assumes `value->len` is uint64 but on armhf size_t is `unsigned int` or uint32.

```c
static inline void blob__encode(const blob_t *value, void **cursor)
{
 size_t len = byte__pad64(value->len);
 uint64__encode(&value->len, cursor);
 memcpy(*cursor, value->base, value->len);
 *cursor += len;
}
```

**Comment by freeekanayaka** [comment]
Good catch, hope the above PR fixes the issue, however I'm not entirely sure, so please feel free to re-open if it doesn't. If you can test it and let me know, I'll possibly cut a new release.

**Comment by ibuildthecloud** [comment]
@freeekanayaka Thanks, we'll test out the fix and let you know.
