### ISSUE TITLE
How to backup

### ISSUE THREAD

**Issue by ibuildthecloud** [canonical/dqlite#193]
What's the best approach to do backups on a live cluster?

**Comment by freeekanayaka** [comment]
If you copy the data directory of the leader at any time (it can be done concurrently while the leader is operating), you can be sure you'll be able to recover the state the cluster had at the time the copy was made. The leader might commit some new entries **while** the copy is being run, depending on the timing those could be included in the copy or not, in any case the copy will be consistent, so when you restore it you will either have those entries or not, but it will be a consistent state. You can also copy the data directory of a non-leader node and achieve about the same effect, with the only difference that if that node is lagging a bit behind the actual commit index of the leader you might lose some commits (however this is unlikely in practice).

**Comment by ibuildthecloud** [comment]
Perfect, thanks!
