### ISSUE TITLE
Node ID overflow/truncate

### ISSUE THREAD

**Issue by ibuildthecloud** [canonical/dqlite#199]
The node ID in go-dqlite is uint64 but it seems if you use a very large number the ID later returned in the client.Cluster() call is different.

Example:
```
$ dqlite-demo start 1 &
# dqlite-demo start 1210777256789200816 -a 127.0.0.1:9182 &
$ dqlite-demo add 1210777256789200816 -a 127.0.0.1:9182
$ dqlite-demo cluster
ID 	Leader 	Address
1 	true 	127.0.0.1:9181
84594608 	false 	127.0.0.1:9182
```

I believe 84594608 is 1210777256789200816 if you set the first 32 bytes to 0.

**Comment by ibuildthecloud** [comment]
I think this issue has lead to some problems I've seen.  Because when we join a node we make sure the node ID matches but I think dqlite is using a number like 1210777256789200816 but then we read 84594608 from the API and use 84594608.  Then it doesn't seem to really be a part of the cluster, I'm assuming because the node IDs don't match.

For a fix on my side I've just switched to using node IDs in the 32bit range.

**Comment by freeekanayaka** [comment]
This issue should be solved in the latest changes in the C raft library. I'll need to do matching changes in dqlite itself, but that will come shortly. There will also be new helpers to generate unique IDs for new node, based on a hash of the node address and current time.
