### ISSUE TITLE
Question: Is it possible to have one DB replicated and another non replicated in one app?

### ISSUE THREAD

**Issue by ns-gzhang** [canonical/dqlite#213]
We have different SLO for different data types, based on trade-off of performance and data reliability. Some data requires replication for higher reliability, while some other can have possible loss but require low latency. If we could configure three types of databases at the same time: replicated, non-replicated, in-memory only, that will be great! Can I achieve that? Thanks!

**Comment by freeekanayaka** [comment]
You currently can't have that level of granularity at the single database level. You can however use different databases, one with Dqlite (replicated), one with SQLite backed by a file (non-replicated) and one with SQLite backed by memory (with the ```:memory:``` special filename).

**Comment by ns-gzhang** [comment]
Thank you Free. So I just need to use the go-sqlite3 driver to bypass dqlite for the non-replicated use cases, and they can co-exist. Sounds great!

**Comment by freeekanayaka** [comment]
Yes, they can co-exist. If you are using both go-dqlite and go-sqlite3, please don't forget to run [ConfigMultiThread()](https://godoc.org/github.com/canonical/go-dqlite#ConfigMultiThread), for example calling it in an init() function in your main package.

**Comment by ns-gzhang** [comment]
Great. Thanks for the tips.
