### ISSUE TITLE
Help using the library?

### ISSUE THREAD

**Issue by jeromegn** [canonical/dqlite#218]
I'm writing a rust crate with bindings to dqlite. In theory that should be very easy given the small surface area of this library.

However, I keep getting DQLITE_MISUSE errors trying to bind to an address. I'm just passing "127.0.0.1:5005" as soon as I create the node (I didn't try starting it or anything).

This is the current minimal state of the project: https://github.com/jeromegn/libdqlite-sys/blob/master/src/lib.rs

See the `e_to_e` for an example on how I'm expecting it to be used.

What am I doing wrong?

It's unclear if libdqlite expects NUL-byte terminated strings. I tried both but kept getting the same error code so I figure it must be something else.

Edit: Our use case will be replicating state across many different servers.

**Comment by freeekanayaka** [comment]
Yes, libdqlite expect standard NULL-terminated C strings.

I didn't try with rust, but I can't quite reproduce your issue with plain C.

I wrote a `main.c` server with:

```C
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <dqlite.h>

int main() {
  const char *address = "127.0.0.1:5005";
  const char *dir = "/tmp/dqlite-rs";
  dqlite_node *node;
  int rv;
  mkdir(dir, 0755);
  rv = dqlite_node_create(1, address, dir, &node);
  if (rv != 0) {
    printf("dqlite_node_create: %d\n", rv);
  }
  rv = dqlite_node_set_bind_address(node, address);
  if (rv != 0) {
    printf("dqlite_bind_address: %d\n", rv);
  }
  rv = dqlite_node_start(node);
  if (rv != 0) {
    printf("dqlite_node_start: %d\n", rv);
  }
  pause();
}
```

which I compiled and started with:

```bash
gcc main.c -o main -ldqlite && ./main
```

That starts fine. I then I wrote a minimal Go `main.go` client with:

```go
package main

import (
	"context"
	"database/sql"
	"log"

	"github.com/canonical/go-dqlite/client"
	"github.com/canonical/go-dqlite/driver"
)

func main() {
	store := client.NewInmemNodeStore()
	store.Set(context.Background(), []client.NodeInfo{{Address: "127.0.0.1:5005"}})
	driver, err := driver.New(store)
	if err != nil {
		log.Fatal(err)
	}
	sql.Register("dqlite", driver)
	db, err := sql.Open("dqlite", "test.db")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	_, err = db.Exec("CREATE TABLE IF NOT EXISTS foo(n INT)")
	if err != nil {
		log.Fatal(err)
	}
}
```

and ran it with:

```bash
go run -tags libsqlite3 main.go
```

The client ran fine without reporting errors.
