### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [canonical/dqlite#220]
Would you like to [replace more defines for constant values](https://github.com/canonical/dqlite/blob/6789f6c9518ff80f7f61627ab40f309c4ba5045b/src/protocol.h#L28 "Update candidate") by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages "Description for enumerated types") to stress their relationships?

**Comment by stgraber** [comment]
@MathieuBordere what do you think?

**Comment by MathieuBordere** [comment]
Replacing the defines by enums is somewhat cleaner imo, so that would be fine for me.
