### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [canonical/dqlite#222]
Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_lock](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html "Lock a mutex") ⇒ [vfs__x_close](https://github.com/canonical/dqlite/blob/fb0cee6897ea4cfff750ac13636d3c680a22f9ec/src/vfs.c#L640)
- [sqlite3_malloc](https://www.sqlite.org/c3ref/free.html "Memory allocation") ⇒ [dqlite_node_create](https://github.com/canonical/dqlite/blob/465522bdcd9c7320e6585e7145f8425beb8c406f/src/server.c#L138)

**Comment by freeekanayaka** [comment]
The `pthread_mutex_lock` call is legacy and can probably be removed, because that code shouldn't be accessed by multiple threads these days.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to [detect every error situation as early as possible](https://github.com/canonical/dqlite/blob/0132888536f2f06020eef7533fc5ef61b29f78be/src/server.c#L87 "Update candidate: dqlite__init()")?
