### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [canonical/dqlite#223]
Would you like to add the configuration script “[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads")” to [your build specification](https://github.com/canonical/dqlite/blob/587ccf0d331670ce1dc26a7b52f8a7e081a1c2a8/configure.ac#L80 "Update candidate")?

**Comment by stgraber** [comment]
We seem to have it now.

**Comment by elfring** [comment]
Will such [a build script adjustment](https://github.com/canonical/dqlite/commit/31704321e4ac20334358e7bcd20cc57a139143c1#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810R12 "Use AX_PTHREAD to configure pthread support") trigger any further software development considerations?
