### ISSUE TITLE
Would DQlite add an optional extension to use LMDB or LSM1 as the DB storage engine  

### ISSUE THREAD

**Issue by wongjlm** [canonical/dqlite#234]
Would DQlite add an optional extension to use LMDB or LSM1 as the DB storage engine to improve the DB performance?

**Comment by freeekanayaka** [comment]
I don't think using LMDB would improve performance, actually the opposite. See the comment I made [here](https://github.com/canonical/raft/issues/130#issuecomment-615321327). Quoting from there:

> >  The last thing that I have seen is that the hashicorp/raft library comes with an official MDBStore backend, as I am the author of heed: a safe typed LMDB wrapper in Rust, I will probably make an equivalent store on top of LMDB using heed.
>>  Does that make sense to you?
>
> In my opinion the disk persistence story is one point where this raft library shines over hashicorp/raft. I believe the stock storage implementation of hashicorp/raft uses boltdb, and there's the additional LMDB implementation. Both of them are key-value stores, and as such they are actually not such a great fit for implementing a raft storage backend IMO. Essentially because they add functionality that you don't need, and which probably hurts performance (I don't have numbers). Also, botldb and most probably also LMDB are not using asynchronous and non-blocking disk I/O, something which is very important these days to get high performance in a multi-core SSD-backed world.
>
> The storage implementation of the libuv backend in this raft library is based on the original design of the Raft author (see here, which is also the design of the other very popular Go implementation, etcd/raft.
>
> The reason why hashicorp/raft went for boltdb or LMDB is probably just because they were off-the-shelve components that they could quickly re-use.

**Comment by freeekanayaka** [comment]
If you need to bump write performance of dqlite, I see a couple of options:

1) Turn off `fsync` in the C raft backend that dqlite uses. This will hugely improve latency of a database write, however it comes at the cost that if you are unlucky enough to lose a majority of nodes right before a log entry was completely persisted to disk, then you might lose one or more committed transactions. It might be such a rare event in practice that you might be willing to accept this tradeoff.

2) An even more aggressive approach would be to not write to disk at all, and have your data live only in-memory. As long as you don't lose or restart a majority of your nodes at the same time, you won't lose data. This is clearly more risky than 1) in terms of potential data loss, but also more performant.

As of now, there's no support for either 1) or 2), but if you need such features just let me know as they would be relatively easy to add.

**Comment by stgraber** [comment]
Closing as we're not planning on adding LMBD/LSM1, if there's interest for any of the other options listed above (disable fsync or run in-memory only), please file an issue and we'll look at doing that.
