### ISSUE TITLE
Would dqlite support non-Linux platform?

### ISSUE THREAD

**Issue by wongjlm** [canonical/dqlite#235]
Do you have a plan to support non-Linux platforms?

May be using: 
 
https://tinyclouds.org/iocp-links.html 

https://github.com/libuv/libuv

**Comment by freeekanayaka** [comment]
The part that is currently Linux-specific is the disk I/O code in the C-raft library that dqlite uses. There's currently [this PR](https://github.com/canonical/raft/pull/119) that should make C-raft work on Windows and MacOS, however the author of that PR has not finished the work yet.

I personally don't have plans yet to support non-Linux platforms, but the above PR shows that it would be relatively straightforward to do, and patches would be welcome.

**Comment by rabits** [comment]
I hope #285 will help with BSD systems :)

**Comment by stgraber** [comment]
Closing as it was just a question which got answered above.
We've been merging BSD/MacOS fixes when provided to us and are also happy to merge fixes needed for any other platform.

We'd also be happy for someone to extend our CI runs on those platforms to make sure we don't regress things.
