### ISSUE TITLE
Please enable more architectures in the devel PPA

### ISSUE THREAD

**Issue by xnox** [canonical/dqlite#236]
https://launchpad.net/~dqlite/+archive/ubuntu/master/+packages?field.name_filter=&field.status_filter=published&field.series_filter=groovy

provides builds for amd64 and arm64. Please configure the PPA to enable armhf ppc64el s390x. It is a self service action that anyone in ~dqlite can do.

Also please request a devirt option on the ppa via ~Launchpad to enable riscv64 builds

**Comment by freeekanayaka** [comment]
Please would you elaborate why you need such builds?

**Comment by xnox** [comment]
lxd is built and supported on all of those architectures and uses dqlite. It is prudent to QA dqlite on all of the architectures that ubuntu supports, especially to ensure that less common ports are well supported, and e.g. there are no endianess and platform specific bugs.

lxd, as downstream from dqlite, shouldn't be debugging platform specific issues with dqlite.

At the moment riscv64 architecture does not yet have a snapstore or snaps. And they are all being bootstrapped from debs.

For example, whilst trying to use lxd, I am currently debugging why dqlite is crashing on riscv64 https://paste.ubuntu.com/p/Xmc8tMGMMt/

Only to discover that dqlite upstream does not do test builds of dqlite on lxd supported architectures armhf ppc64el s390x riscv64, despite being available to the dqlite project.

**Comment by xnox** [comment]
You can also enable more architectures in travis

```
arch: amd64
```
could be expanded into a matrix to cover arm64 s390x ppc64le. Which are btw powered by lxd and use dqlite ;-) might not want to break travis ;-)

https://docs.travis-ci.com/user/multi-cpu-architectures/#testing-on-multiple-cpu-architectures

**Comment by freeekanayaka** [comment]
If the reason is getting more CI coverage across architectures, then Travis seems indeed a more appropriate place/tool. The underlying raft library that dqlite uses already has several architectures enabled on Travis (see [here](https://github.com/canonical/raft/blob/master/.travis.yml#L29), and I plan to go through the same exercise for dqlite.

**Comment by xnox** [comment]
Separately https://dqlite.io/ advertises that

> Runs on ARM, X86, POWER and IBM Z architectures

Yet the stable ppa that is mentioned just above it, only has ARM64 adn X86_64. WIthout ppc64el or s390x enabled.

So there is that as well. There seems to be the missmatch between actual usage, documentation, and what stable & master PPAs build for.

**Comment by stgraber** [comment]
@freeekanayaka enabling all arches on the PPA shouldn't really cost us anything other than LP build time and we have all arches enabled on all the LXC PPAs usually. RISCV64 is the one that's a bit more annoying to enable as for that we need to guarantee that only Canonical employees can push to the PPA (which I think is true in this case).

**Comment by stgraber** [comment]
I've now reconfigured the PPAs to build on all virtualized architectures (no riscv64 yet, may look into devirt later) and also enabled ddebs, so this now matches what's listed on the website.
