### ISSUE TITLE
undefined reference to raft_set_max_catch_up_rounds / raft_set_max_catch_up_round_duration

### ISSUE THREAD

**Issue by AlexAndrascu** [canonical/dqlite#265]
Hi there, 

This is my first attempt at building this so it may be just me.

Building against:

```
uname -opvr
5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 GNU/Linux
```
I'm getting:

```
# github.com/canonical/go-dqlite/internal/bindings
/usr/bin/ld: /usr/local/lib/libdqlite.so: undefined reference to `raft_set_max_catch_up_round_duration'
/usr/bin/ld: /usr/local/lib/libdqlite.so: undefined reference to `raft_set_max_catch_up_rounds'
collect2: error: ld returned 1 exit status
```

Commenting out lines 76-77 in `src/server.c`:

```
	raft_set_max_catch_up_rounds(&d->raft, 100);
	raft_set_max_catch_up_round_duration(&d->raft, 50 * 1000); /* 50 secs */
```
and rebuilding seems to fix it. Unsure about the implications. Can you please advise ?

Many thanks

**Comment by freeekanayaka** [comment]
Are you using the deb packages or building everything from source or a mix of the two?

You probably have an outdated version of `libraft`, commenting those two lines should be harmless if you just want to build and test dqlite.

**Comment by AlexAndrascu** [comment]
Building everything from source, Raft included, as described in the README :)

**Comment by freeekanayaka** [comment]
Are you sure you don't have an out-dated `libraft.so` around? Those functions are definitely there in raft master.

**Comment by AlexAndrascu** [comment]
Not sure enough. It looks like this `libraft.so -> libraft.so.0.0.7` so I think you're right. I can see 0.9 being latest. 

I'll try with that next and reopen if needed. A Dockerfile would come really handy here.

**Comment by freeekanayaka** [comment]
FWIW the `0.0.7` soname version is unrelated to the release version. Regardless, the library object is likely out-of-date as I said.

I'll make a note about providing a Dockerfile.
