### ISSUE TITLE
raft/uv.h not found

### ISSUE THREAD

**Issue by Chaz6** [canonical/dqlite#280]
I have installed raft from https://github.com/canonical/raft/archive/v0.9.25.tar.gz (which appears to be the most recent release) and running `configure` for dqlite completes successfully. On running `make`, the process fails with the following output:-

```
  CC       src/bind.lo
  CC       src/client.lo
  CC       src/command.lo
  CC       src/conn.lo
In file included from src/conn.c:1:
src/conn.h:8:10: fatal error: 'raft/uv.h' file not found
#include <raft/uv.h>
         ^~~~~~~~~~~
1 error generated.
make: *** [src/conn.lo] Error 1
```

**Comment by freeekanayaka** [comment]
Might need a release refresh for both dqlite and raft. If it's ok, please try a checkout from git master for both raft and dqlite, that should build fine.

**Comment by Chaz6** [comment]
Thanks, will do.
