### ISSUE TITLE
Memory spike when taking snapshot

### ISSUE THREAD

**Issue by ktsakalozos** [canonical/dqlite#281]
Periodically and under certain conditions [1] dqlite will take a snapshot [2]. The snapshot ends up copying the memory used in vfs [3] and for a short period of time the memory usage increases by hundreds of MB subject to the dataset. Maybe we should find a way to get this snapshot without spiking the memory? Not sure if this is possible, I am reporting this behavior in case it tips us over in memory constrained environments.

[1] https://github.com/canonical/raft/blob/master/src/replication.c#L1368
[2] https://github.com/canonical/raft/blob/master/src/replication.c#L1410
[3] https://github.com/canonical/dqlite/blob/master/src/vfs.c#L2427

**Comment by MathieuBordere** [comment]
https://github.com/canonical/dqlite/pull/356 should provice a lot of improvement for this case.
