### ISSUE TITLE
Code for dqlite_node_set_network_latency makes no sense.

### ISSUE THREAD

**Issue by athendrix** [canonical/dqlite#286]
```c
int dqlite_node_set_network_latency(dqlite_node *t,
				    unsigned long long nanoseconds)
{
	unsigned milliseconds;
	if (t->running) {
		return DQLITE_MISUSE;
	}
	/* Currently we accept at most 500 microseconds latency. */
	if (nanoseconds < 500 * 1000) {
		return DQLITE_MISUSE;
	}
	milliseconds = (unsigned)(nanoseconds / (1000 * 1000));
	raft_set_heartbeat_timeout(&t->raft, (milliseconds * 15) / 10);
	raft_set_election_timeout(&t->raft, milliseconds * 15);
	return 0;
}
```
Why are we taking nanosecond level input, checking if it's less than 500 microseconds, and then truncating to the millisecond?
Furthermore, we're converting from a unsigned long long to an unsigned, and so we now have several values that are going to have major problems.
Every value < 500000 will correctly return DQLITE_MISUSE,
But values >= 500000 and  < 1000000 will be truncated to give milliseconds a value of 0, which will set the raft heartbeat and election timeout to 0.
Furthermore, because we're casting from an unsigned long long to an unsigned, we have a whole different problem here.
The max value for an unsigned is either 65535 or 4294967295 depending on the environment, but let's assume 4294967295 just to give ourselves as much wiggle room as possible.
we're dividing by 1000000 so any value for nanoseconds above 4,294,967,295,999,999 will cause us overflow problems.
What's the max value for an unsigned long long? 18,446,744,073,709,551,615.
Several orders of magnitude larger.
Any value between 4,294,967,296,000,000 and 18,446,744,073,709,551,615 will cause problems, (and that's before we do any additional arithmetic on it.)
In all these cases, we *should* return DQLITE_MISUSE
We're doing a useless check to see if it's under 500 microseconds that does almost nothing, but have completely neglected a maximum sanity value.

So let's move forward, how do we fix this?
Personally, I'd mark this method as obsolete, and make a new one where the user can pass in milliseconds directly.
Simply check to see if the millisecond value is 0, and maybe add a sanity check of an hour (3600000) or a day (86400000) as a maximum, and return DQLITE_MISUSE in the cases where it doesn't fall between those values. Keep the running check, and then pass it into the raft functions.
The current obsolete method should have a similar maximum check to mirror the millisecond one (to avoid overflow), and then should divide by 1000000 and call the new function.

something like this:
```c
int dqlite_node_set_network_latencyv2(dqlite_node *t, unsigned milliseconds)
{
	if (t->running || milliseconds== 0 || milliseconds > 86400000 ) {
		return DQLITE_MISUSE;
	}
	raft_set_heartbeat_timeout(&t->raft, (milliseconds * 15) / 10);
	raft_set_election_timeout(&t->raft, milliseconds * 15);
	return 0;
}
int dqlite_node_set_network_latency(dqlite_node *t,
				    unsigned long long nanoseconds)
{
	if(nanoseconds > 86400000000000){
		return DQLITE_MISUSE;
	}
	return dqlite_node_set_network_latencyv2(t,(unsigned)(nanoseconds / (1000 * 1000));
}
```

**Comment by athendrix** [comment]
If we want to delve even further into the strangeness
The heartbeat and election timeout defaults are here:
```c
	raft_set_election_timeout(&d->raft, 3000);
	raft_set_heartbeat_timeout(&d->raft, 500);
```
No value passed into set_network_latency can reobtain these default values.
I would suggest changing that to:
```c
	raft_set_heartbeat_timeout(&d->raft, 300);
	raft_set_election_timeout(&d->raft, 3000);
```
so that if someone passes in 200 milliseconds, they would be able to reobtain the default values.
And also swapping the order to be more consistent.

**Comment by MathieuBordere** [comment]
@athendrix Thank you for your valuable input, this function indeed has several problems and must be improved.
