### ISSUE TITLE
Snapshots not being cleaned up

### ISSUE THREAD

**Issue by cjohnston1158** [canonical/dqlite#289]
I'm running microk8s 1.20/stable in a 3 node cluster. The amount of space being consumed by backends is very large compared to my other clusters:

### node01
```
/var/snap/microk8s/2074/var/kubernetes/backend$ du -h . 
4.4G    .
```
### node02
```
/var/snap/microk8s/2074/var/kubernetes/backend$ du -h .
26G     .
```
### node03
```
/var/snap/microk8s/2074/var/kubernetes/backend$ du -h .
4.7G    .
```

ls -l of /var/kubernetes/backend:
[node01](https://paste.ubuntu.com/p/tXmwtvSk5c/)
[node02](https://paste.ubuntu.com/p/zwb8qBdcgJ/)
[node03](https://paste.ubuntu.com/p/T6X6NJDyZN/)

**Comment by MathieuBordere** [comment]
Fix is in https://github.com/canonical/raft/pull/193.

Cleanup of the snapshot files, is not in yet, will open separate PR for it.
