### ISSUE TITLE
Assertion `db->follower == NULL' failed when database reaches certain size

### ISSUE THREAD

**Issue by MathieuBordere** [canonical/dqlite#292]
src/db.c:40: db__open_follower: Assertion `db->follower == NULL' failed

Encountered while doing a lot of writes and the raft snapshot reaches a certain size, in this case the last raft snapshot taken is
`-rw------- 1 mathieu mathieu  1,1G apr 22 14:28 snapshot-1-261120-10839878`

https://github.com/canonical/dqlite/blob/761706678edc42f9bd163e31b933ace72576883b/src/fsm.c#L172 This line fails.

**Comment by MathieuBordere** [comment]
Looks to be caused by https://github.com/canonical/dqlite/blob/761706678edc42f9bd163e31b933ace72576883b/src/fsm.c#L187
returning `778` that is translated to  `disk I/O error` by `sqlite3_errmsg`

**Comment by MathieuBordere** [comment]
@freeekanayaka Just picking your mind here, are there any hard limits on DB size around 1024MB that you are aware of?

**Comment by freeekanayaka** [comment]
> @freeekanayaka Just picking your brain here, are there any hard limits on DB size around 1024MB that you are aware of?

Nothing comes to my mind, but there's surely something fishy going on..

**Comment by MathieuBordere** [comment]
https://github.com/canonical/dqlite/blob/761706678edc42f9bd163e31b933ace72576883b/src/vfs.c#L356 fails with these parameters.
vfsDatabaseGetPage pgno:262146 page_size:4096 n_pages:262144

**Comment by MathieuBordere** [comment]
@freeekanayaka I have a fix the problem if I drop this assumption.
https://github.com/canonical/dqlite/blob/761706678edc42f9bd163e31b933ace72576883b/src/vfs.c#L354
Do you have some more insight into why Sqlite appears to violate that assumption?

**Comment by freeekanayaka** [comment]
> @freeekanayaka I have a fix for the problem if I drop this assumption.
> 
> https://github.com/canonical/dqlite/blob/761706678edc42f9bd163e31b933ace72576883b/src/vfs.c#L354
> 
> Do you have some more insight into why SQLite appears to violate that assumption?

I can't claim I'm 100% sure, but I think the reason is that SQLite knows what pages are there and at most it creates a new page by getting a new one past the last one. I don't quite see a reason for skipping pages. However, since you say that relaxing that assumption seems to fix the problem, I'd suggest to create a C-only reproducer and use gdb to see where SQLite is doing that and why.

**Comment by MathieuBordere** [comment]
@freeekanayaka SQLite seems to skip a page when it would attempt to write to offset `PENDING_BYTE` which is `0x40000000` or `1073741824` see https://github.com/sqlite/sqlite/blob/3ff6a5edd97db063258e6df18df4ddbfbdc369bf/src/global.c#L328

also see comment in https://github.com/sqlite/sqlite/blob/3ff6a5edd97db063258e6df18df4ddbfbdc369bf/src/os_unix.c#L3348

```
vfsDatabaseWrite amount:4096 offset:1073737728 page_size:4096 pgno:262144
vfsDatabaseGetPage pgno:262144 page_size:4096 n_pages:524280
** page skipped **
vfsDatabaseWrite amount:4096 offset:1073745920 page_size:4096 pgno:262146
vfsDatabaseGetPage pgno:262146 page_size:4096 n_pages:524280
```

**Comment by freeekanayaka** [comment]
Ah, I didn't know about the pending byte. Perhaps it would make sense to relax the current check just a little bit, to account for this exception, but still keep the check for the general case. Just by 2c.
