### ISSUE TITLE
Rancher's patch

### ISSUE THREAD

**Issue by skerkour** [canonical/dqlite#297]
Hello,
When they tried to use dqlite for k3s, rancher labs produced this patch which seems not to have been upstreamed.

https://github.com/rancher/dqlite-build/blob/master/patch/dqlite-1.diff

Feel free to close if irrelevant.

**Comment by MathieuBordere** [comment]
This patch would cover up issues instead of fixing them, will close. Have resolved some of these problems in meanwhile.
