### ISSUE TITLE
Using multiple databases

### ISSUE THREAD

**Issue by oakes** [canonical/dqlite#300]
I wasn't able to find this in the docs but I noticed [this TODO](https://github.com/canonical/dqlite/blob/0d17e7f306e6a9abd7c1f59cd1c1b035da93f3c6/src/gateway.c#L79) which indicates you need a separate connection for each sqlite database you'd like to use in a cluster. I suppose this will not scale if you have a very large number of separate databases, since that would be a separate TCP connection to the "leader" node for each db. Is that correct or is there a scalable way to use multiple databases? I understand if this is not a use case for the project.

**Comment by freeekanayaka** [comment]
Multiple databases is not something we've been using or supporting, so I expect everything to be sub-optimal. I don't think multiple connections would necessarily be an issue, even a few thousands TCP connections would be okay. What does make you think that a separate TCP connection would be a problem? I think most other databases are also used that way (one connection per db).

**Comment by oakes** [comment]
I was picturing an extreme scenario where there were thousands of different databases. But you make a good point that standalone databases do this as well. Thanks for the quick reply, i look forward to working with this library.
