### ISSUE TITLE
Need libsqlite3-dev to build locally

### ISSUE THREAD

**Issue by shade34321** [canonical/dqlite#303]
When I was trying to work on #287 `./configure` was failing because I didn't have `libsqlite3-dev` installed. I didn't see this mentioned in the build section. I can update the README if you'd like.

**Comment by stgraber** [comment]
Ah yeah, it should be mentioned in the Build section of the README.

A PR adding it there would be great!

**Comment by shade34321** [comment]
Sure thing, is there a minimum version that is needed?

**Comment by stgraber** [comment]
Not that I know of, at least anything from the past 3-4 years has worked.
