### ISSUE TITLE
Reclaiming memory used by deleted rows

### ISSUE THREAD

**Issue by ktsakalozos** [canonical/dqlite#308]
I am inserting a row and deleting it immediately afterwards. The memory footprint increases and stabilizes in rather high values and is not reclaimed.

The attached file is a patch to the dqlite-demo application [dqlite.delete.issue.patch.gz](https://github.com/canonical/dqlite/files/6596021/dqlite.delete.issue.patch.gz). When a POST request is received the same row is added and deleted several times. This load on my laptop causes the memory usage to grow to 360MB and does not drop afterwards. On MicroK8s a similar workload causes the dqlite memory to go over 2GB.

**Comment by MathieuBordere** [comment]
This looks to be related to the way the raft log works. The memory is allocated here https://github.com/canonical/dqlite/blob/0d58b4d9bd3eec46b685cfaeae3bad69981e426a/src/leader.c#L325 and then the command is added to the raft log that only frees it once the entry is removed from the log.

This explains why the memory usage grows until a certain level (max size of log reached) and stays stable afterwards.

By default, dqlite configures raft to keep around 8192 entries in the log before the last snapshot https://github.com/canonical/dqlite/blob/0d58b4d9bd3eec46b685cfaeae3bad69981e426a/src/server.c#L68 This would keep around a large amount of potentially large buffers, if the data row you're inserting is large (which is the case here). In a local test I've adapted dqlite with
```
raft_set_snapshot_threshold(&d->raft, 64);
raft_set_snapshot_trailing(&d->raft, 256);
```

and the large memory footprint disappears. I'm aware that these parameters are not easily adaptable (for now at least) and I also need to think of other consequences/side-effects of adapting these parameters.

**Comment by MathieuBordere** [comment]
@freeekanayaka You have some insights on potential pitfalls when playing with these parameters?

**Comment by freeekanayaka** [comment]
> @freeekanayaka You have some insights on potential pitfalls when playing with these parameters?

If you reduce the trailing amount, you'll need to send a full snapshot in case a follower falls behind the last log entry retained, while if you still have those entries you just need to send those. It might be that the current default value is too large for this particular use case, but I'd reduce it only if it creates actual memory issues.

**Comment by stgraber** [comment]
Making this configurable through the go client may be useful, so users which deal with potential very large transactions can reduce the number of entries whereas those with very small transactions (like LXD) can instead keep a larger set.

**Comment by ktsakalozos** [comment]
Making this value configurable would be great. Can this value change at runtime (maybe with a restart)? Should this config value be shared across all nodes? 

Although it is hard for a user/admin to know if a follower is falling behind or to predict what the average row size might be, he might be able to tell you how much memory the database should consume. Maybe we could have a lower limit on the number of raft entries (eg 2k) and a user provided hint on the memory footprint we should target?

I guess the log entries (snapshot_trailing) should be larger than the snapshot_threshold, right? If we make the snapshot_trailing configurable shouldn't we also allow the user to configure the snapshot_threshold?

**Comment by MathieuBordere** [comment]
The values cannot be changed at runtime, raft doesn't store these values between restarts, it will be similar to how https://github.com/canonical/dqlite/blob/0d58b4d9bd3eec46b685cfaeae3bad69981e426a/include/dqlite.h#L124 is used via the go client in https://github.com/canonical/go-dqlite/blob/7071b960867314b04606a831ad8ffaa08d6b6c9d/internal/bindings/server.go#L148 

Yes, I would make both values, `snapshot_trailing` & `snapshot_threshold` configurable. `snapshot_trailing` should be larger then or equal to `snapshot_threshold`, in this case when the last snapshot is unusable for some reason on a node, all the log entries are still there to restore the data from the second to last snapshot.

These values can be different across nodes.

> Maybe we could have a lower limit on the number of raft entries (eg 2k) and a user provided hint on the memory footprint we should target?
You mean that raft would determine the value of these parameters based on the user hint?

**Comment by ktsakalozos** [comment]
> The settings should be set before starting the node.

Can the values be changed during a restart? Can I stop the database, set the entries to a new value and start the database again? I was thinking that in a single node cluster or even in clusters we could reduce the number of the in-memory entries.


> You mean that raft would determine the value of these parameters based on the user hint?

That is right. For example, the user may ask for 100MB memory footprint, if there is a follower falling behind maybe dqlite can demote that node. Similarly, if the rows are short the memory footprint should be small and thus dqlite may decide to keep more entries in memory. Overall it is hard for someone outside dqlite to indirectly control the memory footprint by setting the number of in-memory entries.

**Comment by MathieuBordere** [comment]
> Can the values be changed during a restart? Can I stop the database, set the entries to a new value and start the database again? I was thinking that in a single node cluster or even in clusters with no followers we could reduce the number of the in-memory entries.

That should be possible, however, a simple test that starts a node, stops and starts it again seems to fail. Will fix that in meanwhile.

**Comment by MathieuBordere** [comment]
@ktsakalozos  Latest `go-dqlite` supports an app with a `WithSnapshotParams` option, example https://github.com/canonical/go-dqlite/blob/b2e31f3be6fe782804f49b3ed403148da23bba93/app/app_test.go#L873 The minimum value is 1024 and should be `Trailing` >= `Threshold`

It's also probable that the latest `go-dqlite` master will have broken your builds, you should allow `-Wl,-z,now` `CGO_LDFLAGS` like this
`export CGO_LDFLAGS_ALLOW="-Wl,-z,now"`
