### ISSUE TITLE
Is dqlite support one NODE with non-vote followers ?

### ISSUE THREAD

**Issue by calvin2021y** [canonical/dqlite#319]
The case is setup one node as leader, so there is no election and voting process.

And also there is like 5 followers automatic sync to this one leader.

I want this because I want avoid use mutex/lock,  for the best write performance. 

The followers will provide read transaction, so the leader write transaction will not blocked by reader or lock.

I plan to use it without go, and use c function to do the query. 

Is DQlite support this kind setup ?

**Comment by stgraber** [comment]
In general I don't see a design problem with running a cluster with one voter and a bunch of followers.
However, dqlite currently does not support distributed reads, so what you actually want to do with such a setup isn't currently possible.

We've talked about distributed reads in the past and it's something we're likely to add in the future. There is some difficulty there if you want data consistency.

Some will want such a setup to save bandwidth but still want a consistent dataset, in which case, we'd want to have an operation go through the leader to indicate an upcoming read through another node, this would prevent write operations during that time. The node that the read goes through would then need to ensure it's not behind the leader and after serving that read, the leader would be told to unlock.

Others, like you, will not care if a read is potentially returning slightly old data and want distributed reads primarily to reduce latency. In this case, we only need to make sure that there is no local operation on the node serving the read which could interfere with it (I believe snapshots were thought to be a potential issue).

@freeekanayaka may remember some more details from that discussion

**Comment by calvin2021y** [comment]
I don't care it return  slightly old data and the query should finished in the sync execute.  I guess in this case snapshots will not be a issue.

**Comment by freeekanayaka** [comment]
> In general I don't see a design problem with running a cluster with one voter and a bunch of followers.
> However, dqlite currently does not support distributed reads, so what you actually want to do with such a setup isn't currently possible.
> 
> We've talked about distributed reads in the past and it's something we're likely to add in the future. There is some difficulty there if you want data consistency.
> 
> Some will want such a setup to save bandwidth but still want a consistent dataset, in which case, we'd want to have an operation go through the leader to indicate an upcoming read through another node, this would prevent write operations during that time. The node that the read goes through would then need to ensure it's not behind the leader and after serving that read, the leader would be told to unlock.

You don't actually **need** to lock writes (although you could), all you need to do to avoid stale reads is that no new write has already been executed by the leader by the time the follower serves the read response. For that, a "ping" to the leader to ask about recency is enough (you can find the details in the Raft paper).

> 
> Others, like you, will not care if a read is potentially returning slightly old data and want distributed reads primarily to reduce latency. In this case, we only need to make sure that there is no local operation on the node serving the read which could interfere with it (I believe snapshots were thought to be a potential issue).

Taking a snapshot should be fine, installing it would be not. I think you are referring to checkpoints, rather than snapshots though. And yes, those will likely need some care.

**Comment by MathieuBordere** [comment]
Will close this for now.
