### ISSUE TITLE
sqlcipher

### ISSUE THREAD

**Issue by krzysztofantczak** [canonical/dqlite#32]
Hello,

Is it possible to use dqlite with sqlcipher?

**Comment by freeekanayaka** [comment]
Hello,

if sqlcipher works with WAL journalling mode (```PRAGMA journal_mode=wal```), I see no reason why it should not be possible. I didn't look at the sqlcipher patch though, do you have a link to it? They don't seem to publish one.

In any case, you could apply on top of the sqlcipher git tree the [replication patch](https://github.com/CanonicalLtd/sqlite/commit/2a9aa8b056f37ae05f38835182a2856ffc95aee4) that dqlite depends on, compile and modify the dqlite demo program under ```testdata/demo.go``` to use encryption, and see if it works.

**Comment by krzysztofantczak** [comment]
Yes, it works with WAL. As for the other part - no idea. At this moment i'm using it thru https://github.com/xeodou/go-sqlcipher - so... i'm not that much on to low level stuff yet.

**Comment by freeekanayaka** [comment]
If you use go-sqlcipher you should be able to use dqlite by:

1. get the sqlcipher code base
2. apply the dqlite replication patch that I mentioned above to sqlcipher's fork of the sqlite code (you might want to ask them help here as they probably have their own scripts to maintain their fork)
3. build the sqlite library from the patched sqlcipher (./configure etc)
4. put the built .so object your library path and build your Go project passing ```-tags libsqlite3``` as build tag, that will make go-sqlcipher use the .so object

If for any reason the dqlite replication patch doesn't apply cleanly, let me know, and I'll see what I can do.

**Comment by krzysztofantczak** [comment]
Ok, this is what i have tried so far: https://gist.github.com/krzysztofantczak/6f2816b6206ec7b72bed8af45e6b786a

And that's the result:
```
error: patch failed: src/pager.c:4103
error: src/pager.c: patch does not apply
error: patch failed: src/pager.h:178
error: src/pager.h: patch does not apply
error: patch failed: src/sqlite.h.in:8503
error: src/sqlite.h.in: patch does not apply
error: patch failed: src/wal.h:38
error: src/wal.h: patch does not apply
```

**Comment by freeekanayaka** [comment]
Yeah that's expected. Maybe I was not clear enough in my previous comment. The sqlcipher code base does not to be a normal fork of the sqlite source tree (in that case the dqlite patch should mostly work), they appear to have their own way to get the sqlite source tree and patching it. I don't know the details of how that works, that's why I suggested that you ask the slqcipher guys what's the best way to apply a patch to their sqlite fork. You can for example link the dqlite patch, or even point them to this issue.

**Comment by krzysztofantczak** [comment]
Ok, after some manual changes, i was able to build .so file. Not sure if it will work as expected, but... I'll try to create some test app with it end report my results if You want.

**Comment by freeekanayaka** [comment]
Great, let me know.

**Comment by paulstuart** [comment]
@krzysztofantczak -- any results to share with the project?
