### ISSUE TITLE
question about entry log size!

### ISSUE THREAD

**Issue by calvin2021y** [canonical/dqlite#322]
If I have a table with a lot record, then I run this query:

```sh
UPDATE tab SET stat=1;
```

If the table  use 10K page, then the log entry size will be 10K*4096 = 40M ?

**Comment by freeekanayaka** [comment]
It depends how many records in that table actually need to be changed because of that query.

If at least one record in everyone of those 10k pages need to be changed, then your calculation is roughly correct (the log entry will be a bit bigger than that because of metadata).

**Comment by calvin2021y** [comment]
thanks for explain!
