### ISSUE TITLE
Intermittent "no known leader" error

### ISSUE THREAD

**Issue by balchua** [canonical/dqlite#335]
I have been experiencing no known leader error, when randomly killing the leader.

The application is packaged in a container, deployed in a multi-node MicroK8s.  Sometimes killing the leader does not seem to transfer the leadership, all other nodes will start reporting no leader found.

This is how the [base image](https://github.com/balchua/bop-bag/blob/main/Dockerfile.base) containing dqlite is built. 

After sometime (a long time, several minutes) the cluster will form, i think it is due to the context timeout i setup (after 2mins) the dqlite node will restart.

I am using the latest `libraft` and `dqlite` using the this repo `ppa:dqlite/master`
This is running on 3 LXD instances.  

_Note: 
The strange thing is when deploy the application on a single node kubernetes im finding it hard to reproduce.
Running locally on host does not present the same behavior.
I have seen this behavior before this PR https://github.com/canonical/raft/pull/235 happening on single node Kubernetes (MicroK8s), but have since unable to reproduce it on single node_

**Comment by balchua** [comment]
I have enabled the logs on all 3 nodes.  At this time, all the nodes seem to report "no known leader".  Before this state happened, the leader was `bopbag-0`.  And I deleted the pod `bopbag-0`.

[bopbag-0.log](https://github.com/canonical/dqlite/files/7446123/bopbag-0.log)
[bopbag-1.log](https://github.com/canonical/dqlite/files/7446124/bopbag-1.log)
[bopbag-2.log](https://github.com/canonical/dqlite/files/7446125/bopbag-2.log)

Mind that i have not built the raft and dqlite from source, i still took the one from the packages.

i went into the pod and checked the version of `libraft-dev` and `libdqlite-dev` and they seem to be the latest.

```shell
root@bopbag-1:/app# apt show libraft-dev -a
Package: libraft-dev
Version: 0.11.2-1~202110291243~ubuntu20.04.1
Priority: optional
Section: libdevel
Source: raft
Maintainer: Free Ekanayaka <free.ekanayaka@canonical.comm>
Installed-Size: 444 kB
Depends: libraft0 (= 0.11.2-1~202110291243~ubuntu20.04.1), libc6-dev
Download-Size: 99.1 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/dqlite/master/ubuntu focal/main amd64 Packages
Description: Raft Consenus protocol development files

root@bopbag-1:/app# apt show libdqlite-dev
Package: libdqlite-dev
Version: 1.9.0-7~202110281651~ubuntu20.04.1
Priority: optional
Section: libdevel
Source: dqlite
Maintainer: Free Ekanayaka <free.ekanayaka@canonical.comm>
Installed-Size: 388 kB
Depends: libdqlite0 (= 1.9.0-7~202110281651~ubuntu20.04.1), libc6-dev, libraft-dev, libuv1-dev, libsqlite3-dev
Download-Size: 71.3 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/dqlite/master/ubuntu focal/main amd64 Packages
Description: dqlite development files
```

it does eventually gain the quorum but it take a long while > 2 mins.

**Comment by MathieuBordere** [comment]
A first observation is that `bopbag_0` is not receiving any raft messages from `bopbag_1` & `bopbag_2` in the logs (timestamps in seconds).
log start: 1635583746
log end:  1635583820

`bopbag_1` receives messages from `bopbag_0` between:
start: 1635583166
end:  1635583734
**15s break**
start: 1635583749
end:  1635583990

`bopbag_2` receives messages from `bopbag_0` between:
start: 1635583670
end:  1635583734
**15s break**
start: 1635583749
end:  1635583986

- So the other nodes receive messages from 0 but not the other way around. Is it possible that due to the node restart something is up with the host `bopbag-0.bopbag-headless`? Does the IP change between restarts? Maybe the old connection is still active and nodes 1 and 2 can send messages to it, but nobody's doing anything with them?

**Comment by MathieuBordere** [comment]
I also see a lot of `src/recv_request_vote.c` in the logs, but in the nodes sending the request vote I would expect a bunch of `src/recv_request_vote_result.c` in the logs, I almost see none.

I think this might be some kind of network (configuration) related issue?

**Comment by balchua** [comment]
Hi @MathieuBordere 
Thanks for looking into this.

> Does the IP change between restarts? Maybe the old connection is still active and nodes 1 and 2 can send messages to it, but nobody's doing anything with them?

Yes ip changes, its running in microk8s.  The 15s gap maybe the cause of the startup probes i have.  If my memory serves me right, kubernetes will wait for a successful startup before allowing requests to reach it.  I can tweak that to a lower value.  But what i find strange is, even if i kill just one pod, isn't it that the other 2 which previously are able to talk to each other will do election even if the leader is unreachable?
So in this case `bopbag-1` and `bopbag-2` should be able to elect a leader? Sorry  I don't have a good grasp of raft tho.

**Comment by MathieuBordere** [comment]
Yes, they should, but they also seem to behave weirdly on the network level.

bopbag-1 logs
```
12164:LIBRAFT   1635583740639603530 src/recv_request_vote.c:32 self:16041049052762475466 from:17515178761066897275@bopbag-2.bopbag-headless:9000 candidate_id:17515178761066897275 disrupt_leader:0 last_log_index:27last_log_term:4 pre_vote:1 term:7
12271:LIBRAFT   1635583746590040060 src/recv_request_vote.c:32 self:16041049052762475466 from:17515178761066897275@bopbag-2.bopbag-headless:9000 candidate_id:17515178761066897275 disrupt_leader:0 last_log_index:27last_log_term:4 pre_vote:1 term:7

more request votes coming in at regular intervals

```

bopbag-2 logs, we see elections starting at the times when bopbag-1 receives the requests
```
LIBRAFT   1635583740584394144 src/tick.c:44 convert to candidate and start new election
LIBRAFT   1635583740584421045 src/convert.c:38 clear follower state
LIBRAFT   1635583740584429350 src/convert.c:23 old_state:1 new_state:2
LIBRAFT   1635583740585869631 src/uv_send.c:218 connection available -> write message
LIBDQLITE 1635583740585918511 impl_connect:168 impl connect id:16041049052762475466 address:bopbag-1.bopbag-headless:9000
LIBRAFT   1635583740585937330 src/uv_send.c:213 no connection available -> enqueue message
LIBDQLITE 1635583740585957749 connect_work_cb:62 connect work cb
LIBDQLITE 1635583740587968829 connect_after_work_cb:138 connect after work cb status 0
LIBRAFT   1635583740588016849 src/uv_send.c:279 connect attempt completed -> status unknown error
LIBRAFT   1635583740588023501 src/uv_send.c:237 send pending messages
LIBRAFT   1635583740588030716 src/uv_send.c:218 connection available -> write message
...
LIBRAFT   1635583746587235739 src/tick.c:72 start new election
LIBRAFT   1635583746588878721 src/uv_send.c:218 connection available -> write message
LIBRAFT   1635583746588969346 src/uv_send.c:218 connection available -> write message
{"level":"info","ts":1635583746.9560504,"caller":"infrastructure/dqlite.go:124","msg":"[dqlite] new connection from %s - [10.1.32.107:56858]"}

```
But I never see log like 
```
src/recv_request_vote_result.c:27 self:16041049052762475466 from:17515178761066897275@bopbag-2.bopbag-headless:9000 term:3 vote_granted:0
```
in the logs of bopbag-2, meaning bopbag-1's messages don't arrive at 2 somehow.

**Comment by balchua** [comment]
Thanks.  I will try to do more experiments with the startupProbeso or remove them entirely.  Lets see if this issue is reduced.
Will keep you posted.

**Comment by balchua** [comment]
Hi @MathieuBordere i can confirm that it has something to do with the networking layer of Kubernetes.

Eventually i use the `hostNetwork` which provides more stable network for dqlite to operate.  In case somebody stumble upon the same issue, the suggestion is to use the `hostNetwork: true` option in the `Pod`.  Which also means that no dqlite pod should run on the same node, otherwise one needs to have different port per dqlite node.

One can find an example manifest [here](https://github.com/balchua/bop-bag/blob/main/manifests/bopbag-multi-node.yaml)

Thank you for your help!
