### ISSUE TITLE
gpg: no valid OpenPGP data found

### ISSUE THREAD

**Issue by bluebrown** [canonical/dqlite#364]
Hi, I am trying to install the package so I can use the go library, but my system doesnt want to install it because no valid OpenPGP data is found.

```
$ sudo add-apt-repository ppa:dqlite/dev
 Automated builds of the latest code in the following repositories:
 - dqlite
 - go-dqlite
 - raft
 More info: https://launchpad.net/~dqlite/+archive/ubuntu/dev
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmp_3dlbc1d/pubring.gpg' created
gpg: /tmp/tmp_3dlbc1d/trustdb.gpg: trustdb created
gpg: key 06CD096F50FB3D04: public key "Launchpad PPA for dqlite" imported
gpg: Total number processed: 1
gpg:               imported: 1
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: no valid OpenPGP data found.
```

```
$ uname -a
Linux WDE-N-W0410 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux

$ cat /etc/os-release | head -n 1
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
```

**Comment by stgraber** [comment]
The error comes from apt-add-repository which isn't something we have any control over.

**Comment by stgraber** [comment]
You can directly get the signing key from https://launchpad.net/~dqlite/+archive/ubuntu/dev and set that up by hand maybe?

**Comment by bluebrown** [comment]
I have looked at this but I am not sure how it works. I could probably figure it out. In any case, the entry barrier is a bit steep imo. At least for me it doesnt seem easy to get going with this project.

**Comment by stgraber** [comment]
The command works perfectly fine on Ubuntu, I suspect what's going on is that you're running a newer apt which doesn't support the old GPG keyrings alongside an older apt-add-repository which doesn't know how to setup the new keyrings.

**Comment by bluebrown** [comment]
Well, I followed some guides, to add the key to a custom location since add-key will be removed in the future. It all worked out ok. 

```bash
# creates /root/.gnupg if it doesn't exist
sudo gpg --list-keys --no-default-keyring

# add the dqlite key to /usr/share/keyrings/
sudo gpg \
    --no-default-keyring \
    --keyring /usr/share/keyrings/dqlite-ubuntu-dev-jammy-archive-keyring.gpg \
    --keyserver hkp://keyserver.ubuntu.com:80 \
    --receive-keys "392A47B5A84EACA9B2C43CDA06CD096F50FB3D04"

# add the dqlite repo pointing to the dqlite key
sudo sh -c "echo 'deb [signed-by=/usr/share/keyrings/dqlite-ubuntu-dev-jammy-archive-keyring.gpg] https://ppa.launchpadcontent.net/dqlite/dev/ubuntu jammy main' \
    > /etc/apt/sources.list.d/dqlite-ubuntu-dev-jammy.list"
```

But now it cannot be installed due to dependecy issues.

```bash
$ sudo apt-get install libdqlite-dev
...
The following packages have unmet dependencies:
 libdqlite0 : Depends: libc6 (>= 2.34) but 2.31-13+deb11u3 is to be installed
```

**Comment by stgraber** [comment]
Right so your distribution's C library is too old to work with the packages from the PPA.

That's mostly expected when you're trying to install packages that were built on Ubuntu for Ubuntu users on Debian.

**Comment by bluebrown** [comment]
I have now installed the libraries from source. Currently via Dockerfile that is used with vscode devcontainer.  Its still causing trouble though.

```Dockerfile
FROM golang

# basic
RUN apt update
RUN apt-get install -y autoconf make

# c raft
RUN git clone https://github.com/canonical/raft.git /tmp/raft
WORKDIR /tmp/raft
RUN apt-get install -y libtool liblz4-dev libuv1-dev
RUN autoreconf -i
RUN ./configure
RUN make
RUN make install

# dqlite
RUN git clone https://github.com/canonical/dqlite.git /tmp/dqlite
WORKDIR /tmp/dqlite
RUN apt-get install -y libsqlite3-dev
RUN autoreconf -i
RUN ./configure
RUN make
RUN make install
ENV CGO_LDFLAGS_ALLOW="-Wl,-z,now"

# sqlite3
WORKDIR /
RUN apt-get install -y sqlite3
```

I am able to compile the go code with `go build -tags libsqlite3 -o app .` but when I want to run it, there is yet again an error:

```bash
./app: error while loading shared libraries: libdqlite.so.0: cannot open shared object file: No such file or directory
```

**Comment by bluebrown** [comment]
The .so file seems to be present. I dont know why its not finding it.

```bash
$ whereis libdqlite.so.0
libdqlite.so: /usr/local/lib/libdqlite.so.0 /usr/local/lib/libdqlite.so
```

**Comment by MathieuBordere** [comment]
try to run `sudo ldconfig` after installing the libraries

**Comment by bluebrown** [comment]
@MathieuBordere, that worked thanks for the hint.
