### ISSUE TITLE
Typo for __BYTE_ORDER__?

### ISSUE THREAD

**Issue by cole-miller** [canonical/dqlite#385]
These ifdefs in src/vfs.c refer to `__BYTE_ORDER` instead of the conventional (?) `__BYTE_ORDER__`:

https://github.com/canonical/dqlite/blob/da62ece640f7ebdf28757dfed615112ee9e7a501/src/vfs.c#L125-L130

Likewise `__BIG_ENDIAN` and `__LITTLE_ENDIAN`. Are those typos?

**Comment by cole-miller** [comment]
Also, I think we should be comparing `__BYTE_ORDER__` to `__ORDER_LITTLE_ENDIAN__` and `__ORDER_BIG_ENDIAN__`, not to `__LITTLE_ENDIAN__` and `__BIG_ENDIAN__`. The latter are boolean constants, so you'd do

```
#if defined(__BIG_ENDIAN__)
#elif defined(__LITTLE_ENDIAN__)
#endif
```

**Comment by freeekanayaka** [comment]
I can't really recall, but please go ahead if there's a more "standard" way to do this.
