### ISSUE TITLE
DQLITE_VERSION_X not matching with release 1.11.X

### ISSUE THREAD

**Issue by theRedMercury** [canonical/dqlite#392]
In release 1.11.X 
The file  `include/dqlite.h`  still contain : 

`DQLITE_VERSION_MAJOR 1`

`DQLITE_VERSION_MINOR 10`

`DQLITE_VERSION_RELEASE 0`

**Comment by MathieuBordere** [comment]
Were updating our procedures so this won't happen again in the future.
