### ISSUE TITLE
DQLITE_RESPONSE_ROWS: Documentation lacks mention of column names

### ISSUE THREAD

**Issue by FGasper** [canonical/dqlite#399]
Hello,

Dqlite’s protocol documentation, when describing the “Batch of table rows” response, doesn’t mention the data structure before the rows that gives the column names. It would be helpful, for posterity, for that to be fixed.

**Comment by cole-miller** [comment]
Indeed, this is another area where our docs need updating -- let me see if I can write this up quickly.

**Comment by cole-miller** [comment]
Okay, it's updated -- docs for the "Batch of rows" response now describe the format as follows:

|Type|Value|
| --- | --- |
| uint64|Number of columns|
|text|Name of first column|
|text|Name of second column (if any)|
|...||
|tuple|Column values of the first row in the batch|
|tuple|Column values of the second row in the batch (if any)|
|…||
|uint64|End marker|

**Comment by FGasper** [comment]
Thank you!
