### ISSUE TITLE
DQLITE_RESPONSE_FILES documentation is inaccurate

### ISSUE THREAD

**Issue by FGasper** [canonical/dqlite#403]
The “file” data type should only be described as having *2* fields: the name (a string) and a blob. The file size transmitted is the first part of the blob.

Also, DQLITE_RESPONSE_FILES body has a leading u64 that seems to indicate the number of “file” structures.

**Comment by cole-miller** [comment]
> Also, DQLITE_RESPONSE_FILES body has a leading u64 that seems to indicate the number of “file” structures.

Indeed, I've updated the documentation to reflect this.

> The “file” data type should only be described as having 2 fields: the name (a string) and a blob. The file size transmitted is the first part of the blob.

I don't understand the point you're making here. The description currently in the docs matches what go-dqlite does to parse a file:

> ### file
>
> A single database file. It consists of the file name (in **text** encoding), followed by the file size (in **uint64** encoding) and finally a blob with the file content.

https://github.com/canonical/go-dqlite/blob/b869bdf53ed3fb80bcc8896e57da6384f06749b0/internal/protocol/message.go#L594-L606

**Comment by FGasper** [comment]
A blob is the u64 for size plus the buffer, right?

That being the case, the logic to parse a tuple's blob includes the u64, so notating it separately would suggest there'd be two identical u64s over the wire .. at least, that's what I initially thought.

**Comment by cole-miller** [comment]
I think "blob" is a generic term that just means a sequence of bytes. That's why the leading length field is mentioned explicitly in the description of the file type and the "blob" tuple entry type.

**Comment by FGasper** [comment]
OK. I just found it confusing to see a document use the term “blob” in two conflicting ways. It at least wasn’t hard to suss out what was going on once I looked at the actual bytes sent.

Thanks!
