### ISSUE TITLE
`receive: header: EOF` triggered by LXD

### ISSUE THREAD

**Issue by cole-miller** [canonical/dqlite#413]
@tomponline pointed out this error from LXD CI logs:

https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/8038/arch=arm64,backend=dir,compiler=golang-tip,section=cluster/console#console-section-0

Let's see if we can figure out what if anything is going wrong in dqlite here.

**Comment by MathieuBordere** [comment]
https://github.com/canonical/go-dqlite/pull/186
