### ISSUE TITLE
A better error message attempting to use ATTACH DATABASE

### ISSUE THREAD

**Issue by manadart** [canonical/dqlite#419]
When attempting to use `ATTACH DATABASE`, not supported by Dqlite, the error reports:
```
disk I/O error
```
A more descriptive error would benefit users.

**Comment by freeekanayaka** [comment]
Out of curiosity, why did you try to use `ATTACH DATABASE`? Do you have a use case for that or were you just playing around?

**Comment by manadart** [comment]
For Juju's use-case, we are looking at having a DB per model. 

We were looking at `ATTACH DATABASE` under the assumption that each DB connection would consume an OS thread. We've been told since that this is not the case, so we don't actually need it.
