### ISSUE TITLE
Several singular nodes joined later together

### ISSUE THREAD

**Issue by koh-osug** [canonical/dqlite#553]
I have several singular nodes, some of these nodes might be started without the knowledge that other nodes exists, i.e. the join addresses are empty. Is it safes when these nodes join again a peer network and can they sync each others data?

**Comment by cole-miller** [comment]
A node that's started with an empty join list (and nothing in cluster.yaml) is a "bootstrap node". Such a node automatically turns into a leader when it starts up and unilaterally commits a configuration containing only itself. If you want some additional nodes to be part of a cluster with this bootstrap node, you have to start them up with a join list that includes at least one node that's already part of the cluster. Two bootstrap nodes can never participate in a cluster with each other.On Jan 25, 2024, at 18:33, Karsten Ohme ***@***.***> wrote:﻿
I have several singular nodes, some of these nodes might be started without the knowledge that other nodes exists, i.e. the join addresses are empty. Is it safes when these nodes join again a peer network and can they sync each others data?

**Comment by koh-osug** [comment]
Thanks.
