### ISSUE TITLE
src/uv_truncate.c:45: uvTruncateWorkCb: Assertion `segments != NULL' failed.

### ISSUE THREAD

**Issue by MathieuBordere** [canonical/dqlite#575]
Detected in jepsen run:
https://github.com/canonical/jepsen.dqlite/actions/runs/6188624145/job/16801028094

artifact:
[jepsen-data-append-partition,member-failure.zip](https://github.com/canonical/raft/files/12616404/jepsen-data-append-partition.member-failure.zip)

**Comment by cole-miller** [comment]
Closing since this doesn't seem to occur in Jepsen tests since the fix was merged.
