### ISSUE TITLE
src/uv_truncate.c:58: Assertion `i < n_segments' failed

### ISSUE THREAD

**Issue by jerrytesting** [canonical/dqlite#591]
In the latest commit version: 05a49e0, one assertion failed:  src/uv_truncate.c:58: void uvTruncateWorkCb(uv_work_t *): Assertion `i < n_segments'. 
Attached is the log file [n_segments-assertion-failure.log](https://github.com/jerrytesting/c-raft_bugLogs/blob/main/n_segments-assertion-failure.log). Hope it could help you debug.

**Comment by cole-miller** [comment]
This was fixed by canonical/jepsen.dqlite#138.
